import SwiftUI
import AppKit

struct SettingsView: View {
    @EnvironmentObject private var model: AppModel
    @State private var draft: AppSettings
    @State private var editing: String
    @State private var checks: [String: String] = [:]
    @State private var checking: String?
    @State private var watchtowerNpub = ""
    @State private var newWalletName = ""
    init(settings: AppSettings) { _draft = State(initialValue: settings); _editing = State(initialValue: settings.activeNetwork) }
    private var index: Int { draft.environments.firstIndex(where: { $0.network == editing }) ?? 0 }
    private var environment: EnvironmentSettings { draft.environments[index] }
    private func node(_ chain: String) -> Binding<NodeSettings> {
        Binding(get: { draft.environments[index].nodes[chain] ?? NodeSettings() }, set: { draft.environments[index].nodes[chain] = $0 })
    }
    private func relay(_ position: Int) -> Binding<String> {
        Binding(get: { environment.relays.count > position ? environment.relays[position] : "" }, set: { value in
            while draft.environments[index].relays.count <= position { draft.environments[index].relays.append("") }
            draft.environments[index].relays[position] = value
        })
    }
    private var watchtowers: [Blakeswap_V1_Tower] { model.status?.network == editing ? model.status?.watchtowers ?? [] : [] }
    private var favorites: [String] { environment.favoriteWatchtowers }
    private func toggleFavorite(_ tower: Blakeswap_V1_Tower) {
        if favorites.contains(tower.npub) { draft.environments[index].favoriteWatchtowers.removeAll { $0 == tower.npub } }
        else { draft.environments[index].favoriteWatchtowers.append(tower.npub) }
    }
    private var watchtowerSettings: some View {
        GroupBox("Watchtowers") {
            VStack(alignment: .leading, spacing: 14) {
                Text("Your wallet serves as a watchtower while the app is open. Payout addresses and scripts are generated by your wallet.").font(.caption).foregroundStyle(.secondary)
                Toggle("Show my wallets in the public watchtower list", isOn: $draft.environments[index].publicWatchtower)
                    .accessibilityIdentifier("public-watchtower")
                Text("Off by default. Share your npub directly for private discovery, or opt in to announce all your wallets as watchtowers on this network’s relays. Save settings to apply.").font(.caption).foregroundStyle(.secondary)
                if model.status?.network == editing, let own = model.status?.ownWatchtower, !own.npub.isEmpty {
                    Text("Your npub · \(editing == "testnet" ? "Testnet4" : editing.capitalized)").font(.headline)
                    Text(own.npub).font(.caption.monospaced()).textSelection(.enabled)
                    HStack {
                        Button("Copy my npub") { NSPasteboard.general.clearContents(); NSPasteboard.general.setString(own.npub, forType: .string) }.accessibilityIdentifier("copy-watchtower-npub")
                        Text("Rescue fee: \(percentage(own.bps)) · paid only if used").font(.caption).foregroundStyle(.secondary)
                    }
                } else { Text("Select this trading network and connect your wallet to see its npub.").font(.caption).foregroundStyle(.secondary) }
                Divider()
                Text("Favorite watchtowers").font(.headline)
                HStack {
                    TextField("Watchtower npub", text: $watchtowerNpub).textFieldStyle(.roundedBorder).accessibilityIdentifier("watchtower-npub")
                    Button("Look up & add") {
                        let value = watchtowerNpub.trimmingCharacters(in: .whitespacesAndNewlines)
                        let selected = editing
                        Task {
                            if await model.command("tower.resolve", ["pubkey": value]), selected == editing {
                                if !favorites.contains(value) { draft.environments[index].favoriteWatchtowers.append(value) }
                                watchtowerNpub = ""
                            }
                        }
                    }.disabled(model.busy || watchtowerNpub.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || model.status?.network != editing)
                }
                ForEach(favorites, id: \.self) { npub in
                    HStack {
                        VStack(alignment: .leading, spacing: 4) {
                            Text(watchtowers.first(where: { $0.npub == npub })?.label ?? "Awaiting signed quote").font(.callout)
                            Text(npub).font(.caption2.monospaced()).textSelection(.enabled)
                        }
                        Spacer()
                        Button("Remove") { draft.environments[index].favoriteWatchtowers.removeAll { $0 == npub } }
                    }
                }
                Text("Save favorites to select them when creating offers. Private lookups are encrypted; the provider must be reachable through a shared relay.").font(.caption).foregroundStyle(.secondary)
                Divider()
                Text("Public watchtowers").font(.headline)
                Text("Discovered automatically on this network's configured relays. A signed announcement identifies the provider; it does not guarantee availability.").font(.caption).foregroundStyle(.secondary)
                if watchtowers.filter({ $0.public }).isEmpty { Text("No public watchtowers discovered yet.").foregroundStyle(.secondary).font(.callout) }
                ForEach(watchtowers.filter { $0.public }) { tower in
                    HStack {
                        VStack(alignment: .leading, spacing: 4) {
                            Text(tower.label).font(.callout)
                            Text(tower.npub).font(.caption2.monospaced()).textSelection(.enabled)
                        }
                        Spacer()
                        Button(favorites.contains(tower.npub) ? "Remove favorite" : "Add favorite") { toggleFavorite(tower) }
                    }
                }
            }.padding(10)
        }
    }
    var body: some View {
        VStack(alignment: .leading, spacing: 22) {
            GroupBox("Wallets") {
                VStack(alignment: .leading, spacing: 12) {
                    Text("Each wallet has its own keys and balances on every network. All wallets keep running while the app is open.").font(.caption).foregroundStyle(.secondary)
                    ForEach(draft.wallets.indices, id: \.self) { i in
                        HStack {
                            TextField("Wallet name", text: $draft.wallets[i].name).textFieldStyle(.roundedBorder).accessibilityIdentifier("wallet-name-\(draft.wallets[i].id)")
                            if draft.wallets[i].id == model.profile { Text("Selected").font(.caption).foregroundStyle(.secondary) }
                        }
                    }
                    Text("Edit names and save settings to rename wallets. Keys and balances stay the same.").font(.caption).foregroundStyle(.secondary)
                    HStack {
                        TextField("New wallet name", text: $newWalletName).textFieldStyle(.roundedBorder).accessibilityIdentifier("new-wallet-name")
                        Button("Create wallet") { Task { await model.createWallet(name: newWalletName) } }
                            .disabled(model.busy || newWalletName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || draft != model.settings || draft.wallets.count >= 20)
                            .accessibilityIdentifier("create-wallet")
                    }
                    if draft != model.settings { Text("Save or reload your settings edits before creating a wallet.").font(.caption).foregroundStyle(.secondary) }
                }.padding(10)
            }
            Picker("Trading network", selection: $draft.activeNetwork) {
                Text("Regtest").tag("regtest"); Text("Testnet4").tag("testnet"); Text("Mainnet").tag("mainnet")
            }.accessibilityIdentifier("active-network")
            Picker("Configure", selection: $editing) {
                Text("Regtest").tag("regtest"); Text("Testnet4").tag("testnet"); Text("Mainnet").tag("mainnet")
            }.pickerStyle(.segmented).accessibilityIdentifier("settings-environment")
            Group {
                ForEach(["btc", "blake"], id: \.self) { chain in
                    GroupBox(symbol(chain)) {
                        VStack(alignment: .leading, spacing: 12) {
                            Picker("Backend", selection: node(chain).kind) {
                                Text("Electrum").tag("electrum"); Text("Full-node RPC").tag("rpc")
                            }
                            TextField("Endpoint", text: node(chain).url).textFieldStyle(.roundedBorder).accessibilityIdentifier("\(chain)-endpoint")
                            if environment.nodes[chain]?.kind == "rpc" {
                                TextField("RPC cookie file", text: node(chain).cookie).textFieldStyle(.roundedBorder)
                            } else {
                                TextField("Certificate SHA256 pin (optional)", text: node(chain).certificateSha256).textFieldStyle(.roundedBorder)
                            }
                            HStack {
                                Button("Test connection") {
                                    checking = chain
                                    let selected = editing
                                    let endpoint = environment.nodes[chain] ?? NodeSettings()
                                    Task { let result = await model.checkNode(network: selected, chain: chain, node: endpoint); checks["\(selected)-\(chain)"] = result; checking = nil }
                                }.disabled(checking != nil || (environment.nodes[chain]?.url.isEmpty ?? true))
                                if checking == chain { ProgressView().controlSize(.small) }
                            }
                            if let result = checks["\(editing)-\(chain)"] { Text(result).font(.caption).textSelection(.enabled) }
                            if editing == "testnet" && chain == "blake" && (environment.nodes[chain]?.url.isEmpty ?? true) {
                                Text("No verified public Blake2b Testnet4 indexer is available. Configure your own Electrum server or Knots RPC node.").font(.caption).foregroundStyle(.secondary)
                            }
                        }.padding(10)
                    }
                }
                if environment.nodes.values.contains(where: { $0.kind == "electrum" }) {
                    Text("Electrum operators are trusted for the current chain and complete transaction history. The daemon checks transaction data, block hashes and inclusion proofs; it does not validate the full chain. Use your own full node for consensus validation.").font(.caption).foregroundStyle(.secondary)
                }
                GroupBox("Nostr relays") {
                    VStack(spacing: 10) { ForEach(0..<3) { position in TextField("wss://relay.example", text: relay(position)).textFieldStyle(.roundedBorder) } }.padding(10)
                }
                watchtowerSettings
            }
            if editing == "regtest" { Text("Regtest requires separately running BTC and Blake2b nodes. The app does not start or stop them.").font(.caption).foregroundStyle(.secondary) }
            HStack {
                Button("Reload") { Task { await model.loadSettings() } }.disabled(model.busy)
                Spacer()
                Button("Save settings") {
                    var saved = draft
                    for i in saved.environments.indices { saved.environments[i].relays = saved.environments[i].relays.map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }.filter { !$0.isEmpty } }
                    Task { await model.saveSettings(saved) }
                }.buttonStyle(.borderedProminent).disabled(model.busy).accessibilityIdentifier("save-settings")
            }
        }
    }
}
